### ISSUE TITLE
Error attempting to read GPR data from Yutu 2 rover

### ISSUE THREAD

**Issue by hdanque** [NASA-PDS-Incubator/pds-view#35]
I get errors when trying to open lunar GPR data from the recent data release from the Yutu 2 rover. I would like to view these radar data. 

Data source
http://moon.bao.ac.cn/pubMsg/detail-CE4EN.jsp#
LPR Level 2B Scientific Data

**To Reproduce**
1. Open app. 
2. Select .2BL or .2B
3. Click Profile

**Expected behavior**
I wanted to view the radar profile. 

** Version of Software Used**
PDS4_viewer_mac10_13-1.1

**Test Data / Additional context**
Add test data or any other context about the problem here.
[ChinaLunarRadar.zip](https://github.com/NASA-PDS/pds-view/files/4773039/ChinaLunarRadar.zip)

**Screenshots**
<img width="1199" alt="Screen Shot 2020-06-11 at 12 10 31 PM" src="https://user-images.githubusercontent.com/42480758/84542652-864ac700-acbf-11ea-91c4-89c7ae44a991.png">

**Desktop (please complete the following information):**
- Browser =chrome
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	191.0.0.0.0
  SMC Version (system):	2.28f7

**Applicable requirements**
I downloaded the App from: 
http://sbndev.astro.umd.edu/wiki/PDS4_Viewer

Error when displaying the Table or Profile. 
Now processing a Table_Binary structure: TABLE_0
Warning: field_format 'None' does not conform to PDS4 standards for field 'FRAME_IDENTIFICATION' (full location: 'FRAME_IDENTIFICATION')
Warning: field_format 'None' does not conform to PDS4 standards for field 'TIME' (full location: 'TIME')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'VELOCITY' (full location: 'VELOCITY')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'XPOSITION' (full location: 'XPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'YPOSITION' (full location: 'YPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'ZPOSITION' (full location: 'ZPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'ATT_PITCHING' (full location: 'ATT_PITCHING')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'ATT_ROLLING' (full location: 'ATT_ROLLING')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'ATT_YAWING' (full location: 'ATT_YAWING')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_XPOSITION' (full location: 'REFERENCE_POINT_XPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_YPOSITION' (full location: 'REFERENCE_POINT_YPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_ZPOSITION' (full location: 'REFERENCE_POINT_ZPOSITION')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_ATT_PITCHING' (full location: 'REFERENCE_POINT_ATT_PITCHING')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_ATT_ROLLING' (full location: 'REFERENCE_POINT_ATT_ROLLING')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'REFERENCE_POINT_ATT_YAWING' (full location: 'REFERENCE_POINT_ATT_YAWING')
Warning: field_format 'None' does not conform to PDS4 standards for field 'DataParameter1' (full location: 'DataParameter1')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_WORKING_MODE' (full location: 'RADAR_WORKING_MODE')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_CHANNEL_1_GAIN_MODE' (full location: 'RADAR_CHANNEL_1_GAIN_MODE')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_CHANNEL_1_GAIN_VALUE' (full location: 'RADAR_CHANNEL_1_GAIN_VALUE')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_CHANNEL_2_GAIN_MODE' (full location: 'RADAR_CHANNEL_2_GAIN_MODE')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_CHANNEL_2_GAIN_VALUE_1' (full location: 'RADAR_CHANNEL_2_GAIN_VALUE_1')
Warning: field_format 'None' does not conform to PDS4 standards for field 'RADAR_CHANNEL_2_GAIN_VALUE_2' (full location: 'RADAR_CHANNEL_2_GAIN_VALUE_2')
Warning: field_format 'None' does not conform to PDS4 standards for field 'DataParameter2' (full location: 'DataParameter2')
Warning: field_format 'None' does not conform to PDS4 standards for field 'VALID_DATA_LENGTH' (full location: 'VALID_DATA_LENGTH')
Warning: field_format 'None' does not conform to PDS4 standards for field 'CHANNEL_1_RECORD_COUNT' (full location: 'CHANNEL_1_RECORD_COUNT')
Warning: field_format 'None' does not conform to PDS4 standards for field 'CHANNEL_2_RECORD_COUNT' (full location: 'CHANNEL_2_RECORD_COUNT')
Warning: field_format 'None' does not conform to PDS4 standards for field 'CHANNEL_AND_ANTENNA_MARK' (full location: 'CHANNEL_AND_ANTENNA_MARK')
Warning: field_format 'F.6' does not conform to PDS4 standards for field 'ECHO_DATA' (full location: 'ECHO_DATA -> ECHO_DATA')
Warning: field_format 'None' does not conform to PDS4 standards for field 'QUALITY_STATE' (full location: 'QUALITY_STATE')
Error: An error occurred during data read-in.
Traceback (most recent call last):
  File "pds4_tools/viewer/summary_view.pyc", line 171, in _reify_structure
  File "pds4_tools/extern/cached_property.pyc", line 86, in __get__
  File "pds4_tools/reader/table_objects.pyc", line 362, in data
  File "pds4_tools/reader/read_tables.pyc", line 951, in read_table_data
  File "pds4_tools/reader/read_tables.pyc", line 766, in new_table
  File "pds4_tools/reader/table_objects.pyc", line 400, in set_field
  File "pds4_tools/reader/data.pyc", line 319, in set_field
ValueError: could not broadcast input array from shape (428) into shape (107)

**Comment by jordanpadams** [comment]
@hdanque sorry for the confusion here. this repo is actually for a different (albeit confusingly similar) tool. the tool you are referencing actually has a repo at https://github.com/Small-Bodies-Node/pds4_tools/.

That being said, unfortunately, this the label associated with the product (.2BL) appears to be invalid according to the PDS4 Standard, so our tools are unable to read this data. Because of this, there is really no way for us to know what the metadata "should" be, so there really isn't anything we can do.

I would contact the data provider to see if they have tools that can read or visualize this data. Sorry for the convenience.
