### ISSUE TITLE
Add Matrix to Personas deck

### ISSUE THREAD

**Issue by edwardbarraza** [NASA-PDS-Incubator/pds-view#39]

**Comment by edwardbarraza** [comment]
https://www.figma.com/file/XouR3GnOtjBxHkQ7EGH6S5/Personas?node-id=0%3A1

**Comment by tloubrieu-jpl** [comment]
@edwardbarraza @jordanpadams the link above does not work

**Comment by edwardbarraza** [comment]
Works for me - I'll check permissions later but here is a screenshot
<img width="666" alt="Screen Shot 2021-07-15 at 12 51 23 PM" src="https://user-images.githubusercontent.com/26258411/125848952-39b82c0e-1385-473c-8bb2-6998b8d43074.png">
