### ISSUE TITLE
i am new in this filed, and i want to ask what kind of file should i choose to open  when this software run (i want to read some data as shown below)

### ISSUE THREAD

**Issue by vegetablecatcat** [NASA-PDS-Incubator/pds-view#47]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

![image](https://github.com/NASA-PDS/pds-view/assets/109726876/c6d6b56c-1e74-4548-96f1-af440befa0f2)

### 🕵️ Expected behavior

![image](https://github.com/NASA-PDS/pds-view/assets/109726876/ebab8e46-aa38-4b4b-9d0f-dd1631fee58a)

### 📜 To Reproduce

1.
2.
3.
...

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
@vegetablecatcat you should be able to point it at the .lbl label file, and it will read / process any files being referenced from it.

**Comment by jordanpadams** [comment]
Let me know if you have any additional questions. Other tool that maybe helpful to transform this data into something more usable: https://nasa-pds.github.io/transform/

**Comment by vegetablecatcat** [comment]
Hello,


Thank you for answering my last question. I did chose the .lbl label file as you said, but the software showed "failed to execute&nbsp; script pdsview-script" and i got a&nbsp; .xml&nbsp; file which seems wrong .The details are shown in the email attachment.


I would appreciate it if you could help me with this problem.







1954304157
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NASA-PDS/pds-view"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 上午9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NASA-PDS/pds-view] i am new in this filed, and i want to ask what kind of file should i choose to open  when this software run (i want to read some data as shown below) (Issue #47)





 
Let me know if you have any additional questions. Other tool that maybe helpful to transform this data into something more usable: https://nasa-pds.github.io/transform/

**Comment by jordanpadams** [comment]
@vegetablecatcat unfortunately, this tool does not provide robust support for these types of data. I would recommend trying to use the link to Transform tool above to transform into another viewable format.

**Comment by vegetablecatcat** [comment]
Dear Jordan Padams,


Sorry to bother you again. I have tried the Transform tool to read PDS3 data but an&nbsp; error happened like the picture shows in the email attachment.


Hope you can help me with this problem. Thank you very much.




1954304157
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NASA-PDS/pds-view"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 凌晨1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NASA-PDS/pds-view] i am new in this filed, and i want to ask what kind of file should i choose to open  when this software run (i want to read some data as shown below) (Issue #47)





 
@vegetablecatcat unfortunately, this tool does not provide robust support for these types of data. I would recommend trying to use the link to Transform tool above to transform into another viewable format.

**Comment by vegetablecatcat** [comment]
Dear Jordan Padams,


Sorry to bother you again. I have tried the Transform tool to read PDS3 data but an&nbsp; error happened like the picture shows in the email attachment.



Hope you can help me with this problem. Thank you very much.







1954304157
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NASA-PDS/pds-view"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月8日(星期三) 凌晨1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NASA-PDS/pds-view] i am new in this filed, and i want to ask what kind of file should i choose to open  when this software run (i want to read some data as shown below) (Issue #47)





 
@vegetablecatcat unfortunately, this tool does not provide robust support for these types of data. I would recommend trying to use the link to Transform tool above to transform into another viewable format.
